/*
 * Πιλοτικό dataset. Τα ονόματα προέρχονται από τα ψηφοδέλτια των εκλογών
 * της 25ης Ιουνίου 2023. Περιλαμβάνονται τα οκτώ κόμματα που εξέλεξαν
 * βουλευτές στην αναμέτρηση. Δεν αποτελεί κατάλογο υποψηφίων του 2027.
 */
window.VOTER_GUIDE_DATA = {
  source: "https://www.ertnews.gr/perifereiakoi-stathmoi/kozani/d-makedonia-oi-ekloges-tis-25is-iouniou-2023-me-arithmous/",
  districts: {
    grevena: { label: "Γρεβενών", seats: 1 },
    kastoria: { label: "Καστοριάς", seats: 1 },
    kozani: { label: "Κοζάνης", seats: 4 },
    florina: { label: "Φλώρινας", seats: 2 }
  },
  parties: {
    nd: "Νέα Δημοκρατία",
    syriza: "ΣΥΡΙΖΑ–ΠΣ",
    pasok: "ΠΑΣΟΚ–Κίνημα Αλλαγής",
    kke: "ΚΚΕ",
    elliniki: "Ελληνική Λύση",
    niki: "ΝΙΚΗ",
    plefsi: "Πλεύση Ελευθερίας",
    spartiates: "Σπαρτιάτες"
  },
  candidates: [
    { id:"gia", district:"grevena", party:"nd", name:"Ιωάννης Γιάτσιος", links:[{label:"Vouliwatch",url:"https://vouliwatch.gr/mp/giatsios-ioannis"}], positions:["gia-wildboar"] },
    { id:"sta", district:"grevena", party:"nd", name:"Αθανάσιος Σταυρόπουλος" },
    { id:"kog", district:"grevena", party:"nd", name:"Λαμπρινή Κόγιου" },
    { id:"tzo", district:"grevena", party:"syriza", name:"Φωτεινή Τζουβάρα" },
    { id:"kal", district:"grevena", party:"syriza", name:"Γεώργιος Καλαμαράς" },
    { id:"mpg", district:"grevena", party:"syriza", name:"Χρήστος Μπγιάλας" },
    { id:"sto", district:"grevena", party:"pasok", name:"Ιωάννης Στούπας" },
    { id:"gka", district:"grevena", party:"pasok", name:"Βασίλειος Γκαλόγιαννης" },
    { id:"tsi", district:"grevena", party:"pasok", name:"Αικατερίνη Τσιάνα" },
    { id:"kol", district:"grevena", party:"kke", name:"Ελευθερία Κολίτσα Τσακμακά" },
    { id:"gal", district:"grevena", party:"kke", name:"Δημήτριος Γαλάνης" },
    { id:"kle", district:"grevena", party:"kke", name:"Ιωάννης Κλεισιάρης" },
    { id:"avd", district:"grevena", party:"elliniki", name:"Απόστολος Αβδελάς" },
    { id:"axi", district:"grevena", party:"elliniki", name:"Ελισσάβετ Αξιώτη" },
    { id:"nikg", district:"grevena", party:"niki", name:"Γεώργιος Νικολάου" },
    { id:"sidg", district:"grevena", party:"spartiates", name:"Ευθαλία Σιδηροπούλου" },

    { id:"ant", district:"kastoria", party:"nd", name:"Μαρία Αντωνίου", links:[{label:"Facebook",url:"https://www.facebook.com/maria.antoniou.7906/"},{label:"Βουλή",url:"https://www.hellenicparliament.gr/vouleftes/viografika-stoicheia/?MPId=ef815329-f549-4468-a40f-573c800551b3"}], positions:["ant-fur"] },
    { id:"tzi", district:"kastoria", party:"nd", name:"Ζήσης Τζηκαλάγιας" },
    { id:"kan", district:"kastoria", party:"nd", name:"Αγνή Κανδύλη-Μυκωνιάτη" },
    { id:"tel", district:"kastoria", party:"syriza", name:"Ολυμπία Τελιγιορίδου", links:[{label:"Ιστοσελίδα",url:"https://teligioridou.gr/"}], positions:["tel-gas"] },
    { id:"yag", district:"kastoria", party:"syriza", name:"Κωνσταντίνος Γιαγκόπουλος" },
    { id:"sis", district:"kastoria", party:"syriza", name:"Ιωάννης Σίσιος" },
    { id:"var", district:"kastoria", party:"pasok", name:"Κοσμάς Βαρσάμης" },
    { id:"tsa", district:"kastoria", party:"pasok", name:"Αθηνά Τσαλουκίδου" },
    { id:"nti", district:"kastoria", party:"pasok", name:"Αναστάσιος Ντίνας" },
    { id:"gra", district:"kastoria", party:"kke", name:"Γιαννούλα (Αννέτα) Γραμμένου" },
    { id:"tig", district:"kastoria", party:"kke", name:"Γεώργιος Τίγκας" },
    { id:"sal", district:"kastoria", party:"kke", name:"Αντωνία (Τόνια) Σαλβαρίνα" },
    { id:"pav", district:"kastoria", party:"elliniki", name:"Χρήστος Παύλου" },
    { id:"slt", district:"kastoria", party:"elliniki", name:"Μαρία Σαλτζίδου" },
    { id:"sidk", district:"kastoria", party:"elliniki", name:"Ανέστης Σιδηρόπουλος" },
    { id:"zis", district:"kastoria", party:"niki", name:"Στέλιος Ζήσης" },
    { id:"sar", district:"kastoria", party:"niki", name:"Σοφία Σαρηγιαννίδου" },
    { id:"kou", district:"kastoria", party:"niki", name:"Γεράσιμος Κουσούνης" },
    { id:"ous", district:"kastoria", party:"plefsi", name:"Παναγιώτης Ουσταμπασίδης" },
    { id:"xas", district:"kastoria", party:"spartiates", name:"Πηγή Χασάπη" },

    { id:"kon", district:"kozani", party:"nd", name:"Ευστάθιος Κωνσταντινίδης", links:[{label:"Facebook",url:"https://www.facebook.com/konstantinidisstathis/"}], positions:["kon-transition"] },
    { id:"pap", district:"kozani", party:"nd", name:"Μιχάλης Παπαδόπουλος" },
    { id:"ama", district:"kozani", party:"nd", name:"Γεώργιος Αμανατίδης" },
    { id:"vry", district:"kozani", party:"nd", name:"Παρασκευή Βρυζίδου" },
    { id:"dak", district:"kozani", party:"nd", name:"Γεώργιος Δάκης" },
    { id:"pro", district:"kozani", party:"nd", name:"Ευλαμπία Πρώιου-Βαρζή" },
    { id:"vet", district:"kozani", party:"syriza", name:"Καλλιόπη Βέττα", links:[{label:"Ιστοσελίδα",url:"https://www.vettakalliopi.gr/"}], positions:["vet-lignite"] },
    { id:"kar", district:"kozani", party:"syriza", name:"Θεόδωρος Καρυπίδης" },
    { id:"vat", district:"kozani", party:"syriza", name:"Σωκράτης Βατάλης" },
    { id:"mix", district:"kozani", party:"syriza", name:"Ευθυμία (Έφη) Μιχελάκη" },
    { id:"gks", district:"kozani", party:"syriza", name:"Βασιλική (Βάσω) Γκαστάρη" },
    { id:"pas", district:"kozani", party:"syriza", name:"Κωνσταντίνος Πασσαλίδης" },
    { id:"kuk", district:"kozani", party:"pasok", name:"Παρασκευάς (Πάρις) Κουκουλόπουλος", links:[{label:"Ιστοσελίδα",url:"https://koukoulopoulos.gr/"}], positions:["kuk-timeline"] },
    { id:"zar", district:"kozani", party:"pasok", name:"Λουκάς Ζαρογιάννης" },
    { id:"kam", district:"kozani", party:"pasok", name:"Παναγιώτα Καμαριάδου" },
    { id:"tsr", district:"kozani", party:"pasok", name:"Ελένη Τσιρνάρη" },
    { id:"nik", district:"kozani", party:"pasok", name:"Ισαάκ Νικολαΐδης" },
    { id:"fta", district:"kozani", party:"pasok", name:"Γεώργιος Φτάκας" },
    { id:"kuz", district:"kozani", party:"kke", name:"Θεοδώρα Ματίνα (Τίνα) Κουζιάκη" },
    { id:"moy", district:"kozani", party:"kke", name:"Σταύρος Μωυσιάδης" },
    { id:"dim", district:"kozani", party:"kke", name:"Φωτεινή Δημαράκη" },
    { id:"tri", district:"kozani", party:"kke", name:"Κωνσταντίνος Τριανταφυλλίδης" },
    { id:"the", district:"kozani", party:"kke", name:"Εμμανουήλ Θεοδωρίδης" },
    { id:"egr", district:"kozani", party:"kke", name:"Αβραάμ Έγρες" },
    { id:"lib", district:"kozani", party:"elliniki", name:"Αναστασία Λιβεριάδου" },
    { id:"kot", district:"kozani", party:"elliniki", name:"Ελευθέριος Κωτσιόπουλος" },
    { id:"xei", district:"kozani", party:"elliniki", name:"Κατίνα (Κατερίνα) Χειμωνίδου" },
    { id:"xar", district:"kozani", party:"elliniki", name:"Αναστάσιος Χαραλαμπίδης" },
    { id:"pax", district:"kozani", party:"elliniki", name:"Χαράλαμπος Παπαδόπουλος" },
    { id:"xan", district:"kozani", party:"elliniki", name:"Πέτρος Ξανθόπουλος" },
    { id:"mba", district:"kozani", party:"niki", name:"Κωνσταντίνος Μπαλιάκας" },
    { id:"sism", district:"kozani", party:"niki", name:"Πολυξένη Σισμανίδου" },
    { id:"boz", district:"kozani", party:"niki", name:"Μαρία Μποζίνη" },
    { id:"sam", district:"kozani", party:"niki", name:"Ανέστης Σαμαράς" },
    { id:"pra", district:"kozani", party:"plefsi", name:"Δημήτριος Πράσσας" },
    { id:"kag", district:"kozani", party:"plefsi", name:"Ιφιγένεια Καραγκιουλόγλου" },
    { id:"bar", district:"kozani", party:"plefsi", name:"Γεώργιος Βαρδάκας" },
    { id:"zos", district:"kozani", party:"plefsi", name:"Νίκα Ζωσιμίδου" },
    { id:"xri", district:"kozani", party:"spartiates", name:"Κορνηλία Χριστοφόρου" },

    { id:"pps", district:"florina", party:"nd", name:"Σταύρος Παπασωτηρίου", links:[{label:"Βουλή",url:"https://www.hellenicparliament.gr/Vouleftes/Viografika-Stoicheia/?MPId=4f54b337-5ed4-49e1-8309-b01900d9d1af"},{label:"Facebook",url:"https://www.facebook.com/stavros.papasotiriou/"}], positions:["pps-heating"] },
    { id:"anf", district:"florina", party:"nd", name:"Ιωάννης Αντωνιάδης" },
    { id:"vel", district:"florina", party:"nd", name:"Παυλίνα Βέλτση" },
    { id:"ili", district:"florina", party:"nd", name:"Σοφία Ηλιάδου-Τάχου" },
    { id:"per", district:"florina", party:"syriza", name:"Θεοπίστη (Πέτη) Πέρκα", links:[{label:"Ιστοσελίδα",url:"https://perkapeti.gr/"},{label:"Instagram",url:"https://www.instagram.com/petiperka/"}], positions:["per-transition"] },
    { id:"kwi", district:"florina", party:"syriza", name:"Γεώργιος Κωτακίδης" },
    { id:"bir", district:"florina", party:"syriza", name:"Στέφανος Μπίρος" },
    { id:"kri", district:"florina", party:"syriza", name:"Ειρήνη Κρητικού" },
    { id:"lav", district:"florina", party:"pasok", name:"Λάζαρος Λαβασίδης" },
    { id:"krf", district:"florina", party:"pasok", name:"Διαμαντούλα (Διαμάντω) Κρητικού-Φραντζή" },
    { id:"kard", district:"florina", party:"pasok", name:"Όλγα Καραδάκου" },
    { id:"geo", district:"florina", party:"pasok", name:"Αριστοτέλης (Τέλης) Γεωργιάδης" },
    { id:"vog", district:"florina", party:"kke", name:"Μαρία Βογιατζή" },
    { id:"tor", district:"florina", party:"kke", name:"Παναγιώτα (Γιώτα) Τορλαχίδου" },
    { id:"vys", district:"florina", party:"kke", name:"Ευάγγελος Βυσίνης" },
    { id:"ale", district:"florina", party:"kke", name:"Ευάγγελος Αλεξίου" },
    { id:"gak", district:"florina", party:"elliniki", name:"Δημήτριος Γάκης" },
    { id:"ppl", district:"florina", party:"elliniki", name:"Άννα Παπουλίδου" },
    { id:"tan", district:"florina", party:"niki", name:"Αλεξία Τάντση" },
    { id:"pavf", district:"florina", party:"niki", name:"Βασίλειος Παπαδόπουλος" },
    { id:"xrf", district:"florina", party:"spartiates", name:"Θεόδωρος Χαρατσάρης" }
  ],
  positions: {
    "gia-wildboar": { candidate:"gia", pillar:"Αγροτική οικονομία", issue:"Διαχείριση υπερπληθυσμού αγριόχοιρων", stance:"Ενεργητικός περιορισμός του πληθυσμού με οικονομική αξιοποίηση και αυστηρότερους ελέγχους", actions:["Παροχή κινήτρων προς θηρευτές.","Αξιοποίηση και εμπορία του κρέατος και άλλων παραπροϊόντων.","Αύξηση των δειγματοληπτικών ελέγχων για την προστασία κτηνοτρόφων και καταναλωτών."], evidence:"Σαφής", updated:"06/12/2023", sources:[{label:"Κοινοβουλευτική ερώτηση",url:"https://www.hellenicparliament.gr/UserFiles/c0d5184d-7550-4265-8e0b-078e1bc7375a/12436861.pdf"}] },
    "ant-fur": { candidate:"ant", pillar:"Οικονομία και εργασία", issue:"Κλάδος γουνοποιίας Καστοριάς", stance:"Διατήρηση και οικονομική στήριξη του κλάδου της γούνας και των θέσεων εργασίας του", actions:["Κρατικές παρεμβάσεις ενίσχυσης των εργαζομένων και των επιχειρήσεων του κλάδου.","Σύνδεση της στήριξης με την επιχειρηματικότητα και την εξωστρέφεια της τοπικής οικονομίας."], evidence:"Μερική", updated:"15/10/2025", sources:[{label:"Δημόσια παρέμβαση",url:"https://www.facebook.com/maria.antoniou.7906/videos/3133877196795278/"}] },
    "tel-gas": { candidate:"tel", pillar:"Ενέργεια", issue:"Ενεργειακό δίκτυο Καστοριάς", stance:"Σύνδεση της Π.Ε. Καστοριάς με το δίκτυο φυσικού αερίου σύμφωνα με τον αρχικό σχεδιασμό", actions:["Αναίρεση της αλλαγής σχεδιασμού που, κατά τη θέση της, υπονόμευε τη σύνδεση της περιοχής.","Ολοκλήρωση της πρόσβασης των κατοίκων και επιχειρήσεων στο δίκτυο φυσικού αερίου."], evidence:"Σαφής", updated:"29/07/2022", sources:[{label:"Κοινοβουλευτική ερώτηση",url:"https://syriza.gr/h-olympia-teligioridoy-phgainei-sth-boylh-to-thema-me-thn-allagh-schediasmoy-gia-to-fysiko-aerio-sthn-pe-kastorias/"}] },
    "kon-transition": { candidate:"kon", pillar:"Ενέργεια και εργασία", issue:"Δίκαιη μετάβαση", stance:"Συνταγματική κατοχύρωση ειδικής προστασίας για τις περιοχές της απολιγνιτοποίησης", actions:["Ένταξη της απολιγνιτοποίησης και της Δίκαιης Μετάβασης στη συνταγματική αναθεώρηση.","Θεσμική πρόβλεψη για περιοχές που υφίστανται μεγάλες οικονομικές, κοινωνικές και περιβαλλοντικές αλλαγές."], evidence:"Σαφής", updated:"07/05/2026", sources:[{label:"Δημόσια πρόταση",url:"https://xronos-kozanis.gr/protasi-stathi-konstantinidi-gia-syntagmatiki-katochyrosi-tis-apolignitopoiisis-kai-tis-dikaiis-metavasis/"}] },
    "vet-lignite": { candidate:"vet", pillar:"Ενέργεια και εργασία", issue:"Ρυθμός απολιγνιτοποίησης", stance:"Επιβράδυνση και ανασχεδιασμός της μετάβασης ώστε να προστατευθούν η απασχόληση και η ενεργειακή ασφάλεια", actions:["Αποφυγή πρόωρου κλεισίματος λιγνιτικών μονάδων χωρίς έτοιμο εναλλακτικό παραγωγικό σχέδιο.","Περιορισμός της υποκατάστασης του λιγνίτη από εισαγόμενο φυσικό αέριο.","Ειδικά μέτρα για εργαζομένους, τηλεθέρμανση, αποκατάσταση εδαφών και ενεργειακή επάρκεια."], evidence:"Ισχυρή", updated:"26/06/2026", sources:[{label:"Συνέντευξη για την απολιγνιτοποίηση",url:"https://syriza.gr/kalliopi-vetta-i-periochi-tis-dytikis-makedonias-echei-ginei-koinoniko-peirama-tis-kyvernisis-tis-n-d-synentefxi-sto-kokkino-gia-tin-apolignitopoiisi-s/"}] },
    "kuk-timeline": { candidate:"kuk", pillar:"Ενέργεια και εργασία", issue:"Χρονοδιάγραμμα απολιγνιτοποίησης", stance:"Παράταση της λειτουργίας των λιγνιτικών μονάδων μέχρι να εφαρμοστούν αποτελεσματικά μέτρα μετάβασης", actions:["Παράταση του χρονοδιαγράμματος απόσυρσης των μονάδων.","Σύνδεση του νέου χρονοδιαγράμματος με δείκτες απασχόλησης, εισοδήματος και επενδύσεων στη Δυτική Μακεδονία."], evidence:"Σαφής", updated:"22/09/2025", sources:[{label:"Επίκαιρη ερώτηση",url:"https://energypress.gr/news/apolignitopoiisi"}] },
    "pps-heating": { candidate:"pps", pillar:"Ενέργεια", issue:"Τηλεθέρμανση Αμυνταίου", stance:"Εφαρμογή της συμφωνίας που εξασφαλίζει νέα πηγή θερμικής ενέργειας για την τηλεθέρμανση", actions:["Υλοποίηση της συμφωνίας προμήθειας θερμικής ενέργειας.","Διατήρηση της τηλεθέρμανσης μετά τις αλλαγές στη λειτουργία των λιγνιτικών μονάδων."], evidence:"Σαφής", updated:"22/10/2024", sources:[{label:"Δήλωση στην ΕΡΤ",url:"https://www.ertnews.gr/perifereiakoi-stathmoi/florina/florina-st-papasotiriou-i-symfonia-gia-tin-tilethermansi-antimetopizei-to-xronio-provlima-promitheias-thermikis-energeias-sto-amyntaio/"}] },
    "per-transition": { candidate:"per", pillar:"Ενέργεια και εργασία", issue:"Απολιγνιτοποίηση", stance:"Σταδιακή έξοδος από τον λιγνίτη και αντικατάστασή του από ΑΠΕ — όχι επιστροφή στον λιγνίτη ούτε υποκατάστασή του από φυσικό αέριο", actions:["Διατήρηση και αύξηση των εθνικών και ευρωπαϊκών πόρων της Δίκαιης Μετάβασης.","Χρηματοδότηση ενεργειακών κοινοτήτων και έργων αυτοπαραγωγής για πολίτες, αγρότες και μικρομεσαίες επιχειρήσεις.","Επενδύσεις σε αποθήκευση ενέργειας, αντλίες θερμότητας και καθαρές τεχνολογίες.","Συμμετοχή των τοπικών κοινωνιών και προστασία της απασχόλησης κατά τη μετάβαση."], evidence:"Ισχυρή", updated:"15/07/2025", sources:[{label:"Ερώτηση για την αναθεώρηση του ΠΔΑΜ",url:"https://perkapeti.gr/erotisi-p-perka-thema-anatheorisi-toy-programmatos-dikaiis-anaptyxiakis-metavasis-2021-2027-yponomeysi-tis-energeiakis-metavasis-kai-agnoisi-ton-anagkon-ton-topikon-koinonion/"},{label:"Κοινοβουλευτική ερώτηση για τους πόρους μετάβασης",url:"https://www.hellenicparliament.gr/UserFiles/c0d5184d-7550-4265-8e0b-078e1bc7375a/12350718.pdf"}] }
  }
};
